### ISSUE TITLE
API error PAYMENT_REQUIRED

### ISSUE THREAD

**Issue by 14h4i** [hongquan/vn-open-api-provinces#2]
Has error in https://provinces.open-api.vn/

![image](https://github.com/hongquan/vn-open-api-provinces/assets/84112780/b019fa85-b1c7-4ab4-a48c-e366575040c2)

**Comment by hongquan** [comment]
Sự cố này đã được giải thích: https://quan.hoabinh.vn/post/2024/2/thong-bao-ve-tinh-trang-api-tinh-thanh-viet-nam
